version: '3.1'

services:
  nest-api:
    # image: next:latest
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    command: npm run start:dev

  mongo:
    image: mongo
    restart: always
    ports: [27017:27017]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

  mongo-express:
    image: mongo-express
    restart: always
    ports: [8081:8081]
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_OPTIONS_EDITORTHEME: monokai
      # mongo config
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
